// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: cgf.proto

// CGF — Code Graph Facts. The language-neutral contract between the Go frontend
// (extraction) and the Rust core (IFDS taint). One CgfPackage is emitted per Go
// package. See panopticode/docs/02,03. Boolean-taint MVP; additive-only schema.

package cgfpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Origin int32

const (
	Origin_ORIGIN_USER   Origin = 0
	Origin_ORIGIN_STDLIB Origin = 1
	Origin_ORIGIN_DEP    Origin = 2
)

// Enum value maps for Origin.
var (
	Origin_name = map[int32]string{
		0: "ORIGIN_USER",
		1: "ORIGIN_STDLIB",
		2: "ORIGIN_DEP",
	}
	Origin_value = map[string]int32{
		"ORIGIN_USER":   0,
		"ORIGIN_STDLIB": 1,
		"ORIGIN_DEP":    2,
	}
)

func (x Origin) Enum() *Origin {
	p := new(Origin)
	*p = x
	return p
}

func (x Origin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Origin) Descriptor() protoreflect.EnumDescriptor {
	return file_cgf_proto_enumTypes[0].Descriptor()
}

func (Origin) Type() protoreflect.EnumType {
	return &file_cgf_proto_enumTypes[0]
}

func (x Origin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Origin.Descriptor instead.
func (Origin) EnumDescriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{0}
}

type Generator int32

const (
	Generator_GEN_NONE    Generator = 0
	Generator_GEN_PROTOC  Generator = 1
	Generator_GEN_GQLGEN  Generator = 2
	Generator_GEN_MOCKGEN Generator = 3
)

// Enum value maps for Generator.
var (
	Generator_name = map[int32]string{
		0: "GEN_NONE",
		1: "GEN_PROTOC",
		2: "GEN_GQLGEN",
		3: "GEN_MOCKGEN",
	}
	Generator_value = map[string]int32{
		"GEN_NONE":    0,
		"GEN_PROTOC":  1,
		"GEN_GQLGEN":  2,
		"GEN_MOCKGEN": 3,
	}
)

func (x Generator) Enum() *Generator {
	p := new(Generator)
	*p = x
	return p
}

func (x Generator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Generator) Descriptor() protoreflect.EnumDescriptor {
	return file_cgf_proto_enumTypes[1].Descriptor()
}

func (Generator) Type() protoreflect.EnumType {
	return &file_cgf_proto_enumTypes[1]
}

func (x Generator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Generator.Descriptor instead.
func (Generator) EnumDescriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{1}
}

type VertexKind int32

const (
	VertexKind_IN_PARAM         VertexKind = 0 // param_i        (index = param index; field_path k<=1)
	VertexKind_IN_RECEIVER      VertexKind = 1 // receiver
	VertexKind_IN_GLOBAL        VertexKind = 2 // global_i       (sym = global symbol iid)
	VertexKind_OUT_RETURN       VertexKind = 3 // return_j       (index = return index)
	VertexKind_OUT_PARAM_BYREF  VertexKind = 4 // param_i mutated by-ref
	VertexKind_OUT_FIELD        VertexKind = 5 // field_j of receiver/return aggregate
	VertexKind_CALL_ARG_PORT    VertexKind = 6 // callsite arg   (callsite_id, index = arg index)
	VertexKind_CALL_RESULT_PORT VertexKind = 7 // callsite result(callsite_id, index = result index)
	// W1a. The receiver mutated by-ref. It cannot be OUT_PARAM_BYREF: that index
	// is IN_PARAM-relative and the caller maps it to arg port index+1 whenever
	// arg0_is_receiver (the N3 fix, ifds.rs), so port 0 is unaddressable — a
	// receiver write emitted as OUT_PARAM_BYREF(0) would land on the first real
	// argument. Mirrors the IN direction, where port 0 is Slot::Receiver.
	VertexKind_OUT_RECEIVER_BYREF VertexKind = 8
)

// Enum value maps for VertexKind.
var (
	VertexKind_name = map[int32]string{
		0: "IN_PARAM",
		1: "IN_RECEIVER",
		2: "IN_GLOBAL",
		3: "OUT_RETURN",
		4: "OUT_PARAM_BYREF",
		5: "OUT_FIELD",
		6: "CALL_ARG_PORT",
		7: "CALL_RESULT_PORT",
		8: "OUT_RECEIVER_BYREF",
	}
	VertexKind_value = map[string]int32{
		"IN_PARAM":           0,
		"IN_RECEIVER":        1,
		"IN_GLOBAL":          2,
		"OUT_RETURN":         3,
		"OUT_PARAM_BYREF":    4,
		"OUT_FIELD":          5,
		"CALL_ARG_PORT":      6,
		"CALL_RESULT_PORT":   7,
		"OUT_RECEIVER_BYREF": 8,
	}
)

func (x VertexKind) Enum() *VertexKind {
	p := new(VertexKind)
	*p = x
	return p
}

func (x VertexKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VertexKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cgf_proto_enumTypes[2].Descriptor()
}

func (VertexKind) Type() protoreflect.EnumType {
	return &file_cgf_proto_enumTypes[2]
}

func (x VertexKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VertexKind.Descriptor instead.
func (VertexKind) EnumDescriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{2}
}

type Type_Kind int32

const (
	Type_STRUCT    Type_Kind = 0
	Type_INTERFACE Type_Kind = 1
	Type_ALIAS     Type_Kind = 2
)

// Enum value maps for Type_Kind.
var (
	Type_Kind_name = map[int32]string{
		0: "STRUCT",
		1: "INTERFACE",
		2: "ALIAS",
	}
	Type_Kind_value = map[string]int32{
		"STRUCT":    0,
		"INTERFACE": 1,
		"ALIAS":     2,
	}
)

func (x Type_Kind) Enum() *Type_Kind {
	p := new(Type_Kind)
	*p = x
	return p
}

func (x Type_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_cgf_proto_enumTypes[3].Descriptor()
}

func (Type_Kind) Type() protoreflect.EnumType {
	return &file_cgf_proto_enumTypes[3]
}

func (x Type_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type_Kind.Descriptor instead.
func (Type_Kind) EnumDescriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{7, 0}
}

type CallSite_Kind int32

const (
	CallSite_STATIC         CallSite_Kind = 0
	CallSite_VIRTUAL        CallSite_Kind = 1 // VTA fan-out => multiple callee_iids
	CallSite_INVOKES_REMOTE CallSite_Kind = 2 // callee_iids = [GrpcMethod.iid]
	CallSite_GO             CallSite_Kind = 3
	CallSite_DEFER          CallSite_Kind = 4
	CallSite_BUILTIN        CallSite_Kind = 5
)

// Enum value maps for CallSite_Kind.
var (
	CallSite_Kind_name = map[int32]string{
		0: "STATIC",
		1: "VIRTUAL",
		2: "INVOKES_REMOTE",
		3: "GO",
		4: "DEFER",
		5: "BUILTIN",
	}
	CallSite_Kind_value = map[string]int32{
		"STATIC":         0,
		"VIRTUAL":        1,
		"INVOKES_REMOTE": 2,
		"GO":             3,
		"DEFER":          4,
		"BUILTIN":        5,
	}
)

func (x CallSite_Kind) Enum() *CallSite_Kind {
	p := new(CallSite_Kind)
	*p = x
	return p
}

func (x CallSite_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallSite_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_cgf_proto_enumTypes[4].Descriptor()
}

func (CallSite_Kind) Type() protoreflect.EnumType {
	return &file_cgf_proto_enumTypes[4]
}

func (x CallSite_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallSite_Kind.Descriptor instead.
func (CallSite_Kind) EnumDescriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{12, 0}
}

// Stream data ports: a Send/Recv call on a generated Svc_MethodServer /
// Svc_MethodClient stream. Kind is INVOKES_REMOTE with callee_iids =
// [GrpcMethod.iid]; stream_op distinguishes the port from the open call.
type CallSite_StreamOp int32

const (
	CallSite_STREAM_OP_NONE CallSite_StreamOp = 0
	CallSite_STREAM_OP_SEND CallSite_StreamOp = 1 // Send / SendMsg / SendAndClose
	CallSite_STREAM_OP_RECV CallSite_StreamOp = 2 // Recv / RecvMsg / CloseAndRecv
)

// Enum value maps for CallSite_StreamOp.
var (
	CallSite_StreamOp_name = map[int32]string{
		0: "STREAM_OP_NONE",
		1: "STREAM_OP_SEND",
		2: "STREAM_OP_RECV",
	}
	CallSite_StreamOp_value = map[string]int32{
		"STREAM_OP_NONE": 0,
		"STREAM_OP_SEND": 1,
		"STREAM_OP_RECV": 2,
	}
)

func (x CallSite_StreamOp) Enum() *CallSite_StreamOp {
	p := new(CallSite_StreamOp)
	*p = x
	return p
}

func (x CallSite_StreamOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallSite_StreamOp) Descriptor() protoreflect.EnumDescriptor {
	return file_cgf_proto_enumTypes[5].Descriptor()
}

func (CallSite_StreamOp) Type() protoreflect.EnumType {
	return &file_cgf_proto_enumTypes[5]
}

func (x CallSite_StreamOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallSite_StreamOp.Descriptor instead.
func (CallSite_StreamOp) EnumDescriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{12, 1}
}

type Endpoint_Kind int32

const (
	Endpoint_GRPC    Endpoint_Kind = 0
	Endpoint_GRAPHQL Endpoint_Kind = 1
	Endpoint_HTTP    Endpoint_Kind = 2
)

// Enum value maps for Endpoint_Kind.
var (
	Endpoint_Kind_name = map[int32]string{
		0: "GRPC",
		1: "GRAPHQL",
		2: "HTTP",
	}
	Endpoint_Kind_value = map[string]int32{
		"GRPC":    0,
		"GRAPHQL": 1,
		"HTTP":    2,
	}
)

func (x Endpoint_Kind) Enum() *Endpoint_Kind {
	p := new(Endpoint_Kind)
	*p = x
	return p
}

func (x Endpoint_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Endpoint_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_cgf_proto_enumTypes[6].Descriptor()
}

func (Endpoint_Kind) Type() protoreflect.EnumType {
	return &file_cgf_proto_enumTypes[6]
}

func (x Endpoint_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Endpoint_Kind.Descriptor instead.
func (Endpoint_Kind) EnumDescriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{19, 0}
}

// ---------------------------------------------------------------------------
// Top level: one file per package.
// ---------------------------------------------------------------------------
type CgfPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`                                         // canonical repo id, e.g. "gitlab.example.com/acme/ledger-svc"
	CommitSha     string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`              // bitemporal stamp (doc 03 §4)
	PackagePath   string                 `protobuf:"bytes,3,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`        // Go import path
	SchemaVersion int32                  `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // additive-only (doc 03 §5)
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`                                 // "go"
	Functions     []*Function            `protobuf:"bytes,10,rep,name=functions,proto3" json:"functions,omitempty"`
	Types         []*Type                `protobuf:"bytes,11,rep,name=types,proto3" json:"types,omitempty"`
	ProtoMessages []*ProtoMessage        `protobuf:"bytes,12,rep,name=proto_messages,json=protoMessages,proto3" json:"proto_messages,omitempty"`
	GrpcMethods   []*GrpcMethod          `protobuf:"bytes,13,rep,name=grpc_methods,json=grpcMethods,proto3" json:"grpc_methods,omitempty"`
	GraphqlFields []*GraphqlField        `protobuf:"bytes,14,rep,name=graphql_fields,json=graphqlFields,proto3" json:"graphql_fields,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,15,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CgfPackage) Reset() {
	*x = CgfPackage{}
	mi := &file_cgf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CgfPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CgfPackage) ProtoMessage() {}

func (x *CgfPackage) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CgfPackage.ProtoReflect.Descriptor instead.
func (*CgfPackage) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{0}
}

func (x *CgfPackage) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *CgfPackage) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *CgfPackage) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

func (x *CgfPackage) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CgfPackage) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CgfPackage) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *CgfPackage) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *CgfPackage) GetProtoMessages() []*ProtoMessage {
	if x != nil {
		return x.ProtoMessages
	}
	return nil
}

func (x *CgfPackage) GetGrpcMethods() []*GrpcMethod {
	if x != nil {
		return x.GrpcMethods
	}
	return nil
}

func (x *CgfPackage) GetGraphqlFields() []*GraphqlField {
	if x != nil {
		return x.GraphqlFields
	}
	return nil
}

func (x *CgfPackage) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// ---------------------------------------------------------------------------
// Identity — two-level content hash (doc 03 §2). 32-byte SHA-256.
//
//	iid = hash(repo, package_path, exported_symbol_path, normalized_signature)
//	bid = hash(canonical LocalFlow) embedding callees' iids (NOT bids)
//
// ---------------------------------------------------------------------------
type Ident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iid           []byte                 `protobuf:"bytes,1,opt,name=iid,proto3" json:"iid,omitempty"`
	Bid           []byte                 `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ident) Reset() {
	*x = Ident{}
	mi := &file_cgf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ident) ProtoMessage() {}

func (x *Ident) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ident.ProtoReflect.Descriptor instead.
func (*Ident) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{1}
}

func (x *Ident) GetIid() []byte {
	if x != nil {
		return x.Iid
	}
	return nil
}

func (x *Ident) GetBid() []byte {
	if x != nil {
		return x.Bid
	}
	return nil
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Col           int32                  `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_cgf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{2}
}

func (x *Span) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Span) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Span) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

// ---------------------------------------------------------------------------
// Function
// ---------------------------------------------------------------------------
type Function struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        *Ident                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fqn       string                 `protobuf:"bytes,2,opt,name=fqn,proto3" json:"fqn,omitempty"` // import/path/pkg.Type.Method
	Package   string                 `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`
	Origin    Origin                 `protobuf:"varint,4,opt,name=origin,proto3,enum=panopticode.cgf.Origin" json:"origin,omitempty"`
	Generated bool                   `protobuf:"varint,5,opt,name=generated,proto3" json:"generated,omitempty"`
	Generator Generator              `protobuf:"varint,6,opt,name=generator,proto3,enum=panopticode.cgf.Generator" json:"generator,omitempty"`
	HasBody   bool                   `protobuf:"varint,7,opt,name=has_body,json=hasBody,proto3" json:"has_body,omitempty"` // false => signature-only; core uses default/known leaf
	Span      *Span                  `protobuf:"bytes,8,opt,name=span,proto3" json:"span,omitempty"`
	Signature *Signature             `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	Flow      *LocalFlow             `protobuf:"bytes,10,opt,name=flow,proto3" json:"flow,omitempty"`                      // value-flow sidecar (empty if !has_body)
	BindsTo   [][]byte               `protobuf:"bytes,11,rep,name=binds_to,json=bindsTo,proto3" json:"binds_to,omitempty"` // Endpoint.iid this fn implements (handler<->endpoint)
	// Param indices (flow InParam numbering: receiver excluded, first real param
	// = 0) the core seeds as unconditional taint sources — the endpoint's
	// untrusted args (doc 19). Affects summary_key, NOT bid (doc 20 §4).
	SourceParams  []uint32 `protobuf:"varint,12,rep,packed,name=source_params,json=sourceParams,proto3" json:"source_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_cgf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{3}
}

func (x *Function) GetId() *Ident {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Function) GetFqn() string {
	if x != nil {
		return x.Fqn
	}
	return ""
}

func (x *Function) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Function) GetOrigin() Origin {
	if x != nil {
		return x.Origin
	}
	return Origin_ORIGIN_USER
}

func (x *Function) GetGenerated() bool {
	if x != nil {
		return x.Generated
	}
	return false
}

func (x *Function) GetGenerator() Generator {
	if x != nil {
		return x.Generator
	}
	return Generator_GEN_NONE
}

func (x *Function) GetHasBody() bool {
	if x != nil {
		return x.HasBody
	}
	return false
}

func (x *Function) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *Function) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Function) GetFlow() *LocalFlow {
	if x != nil {
		return x.Flow
	}
	return nil
}

func (x *Function) GetBindsTo() [][]byte {
	if x != nil {
		return x.BindsTo
	}
	return nil
}

func (x *Function) GetSourceParams() []uint32 {
	if x != nil {
		return x.SourceParams
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*Param               `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"` // index i => param_i (receiver is params[0] if method)
	HasReceiver   bool                   `protobuf:"varint,2,opt,name=has_receiver,json=hasReceiver,proto3" json:"has_receiver,omitempty"`
	Returns       []*TypeRef             `protobuf:"bytes,3,rep,name=returns,proto3" json:"returns,omitempty"` // index j => return_j
	Variadic      bool                   `protobuf:"varint,4,opt,name=variadic,proto3" json:"variadic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_cgf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{4}
}

func (x *Signature) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Signature) GetHasReceiver() bool {
	if x != nil {
		return x.HasReceiver
	}
	return false
}

func (x *Signature) GetReturns() []*TypeRef {
	if x != nil {
		return x.Returns
	}
	return nil
}

func (x *Signature) GetVariadic() bool {
	if x != nil {
		return x.Variadic
	}
	return false
}

type Param struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ByRef         bool                   `protobuf:"varint,3,opt,name=by_ref,json=byRef,proto3" json:"by_ref,omitempty"` // pointer/slice/map => eligible OUT_PARAM_BYREF
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_cgf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{5}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Param) GetByRef() bool {
	if x != nil {
		return x.ByRef
	}
	return false
}

type TypeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRef) Reset() {
	*x = TypeRef{}
	mi := &file_cgf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRef) ProtoMessage() {}

func (x *TypeRef) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRef.ProtoReflect.Descriptor instead.
func (*TypeRef) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{6}
}

func (x *TypeRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
type Type struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqn           string                 `protobuf:"bytes,1,opt,name=fqn,proto3" json:"fqn,omitempty"`
	Kind          Type_Kind              `protobuf:"varint,2,opt,name=kind,proto3,enum=panopticode.cgf.Type_Kind" json:"kind,omitempty"`
	Implements    [][]byte               `protobuf:"bytes,3,rep,name=implements,proto3" json:"implements,omitempty"` // iids of interfaces satisfied
	Fields        []*Field               `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`         // index j used by OUT_FIELD / field_j slots
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_cgf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{7}
}

func (x *Type) GetFqn() string {
	if x != nil {
		return x.Fqn
	}
	return ""
}

func (x *Type) GetKind() Type_Kind {
	if x != nil {
		return x.Kind
	}
	return Type_STRUCT
}

func (x *Type) GetImplements() [][]byte {
	if x != nil {
		return x.Implements
	}
	return nil
}

func (x *Type) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_cgf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{8}
}

func (x *Field) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ---------------------------------------------------------------------------
// LocalFlow — the value-flow sidecar (language_facts). Vertices are the only
// things edges connect; dense u32 ids local to the function. Calls are
// BARRIERS: edges go into arg-ports / out of result-ports, never THROUGH a call.
// ---------------------------------------------------------------------------
type LocalFlow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vertices      []*FlowVertex          `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty"`
	Edges         []*FlowEdge            `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Callsites     []*CallSite            `protobuf:"bytes,3,rep,name=callsites,proto3" json:"callsites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalFlow) Reset() {
	*x = LocalFlow{}
	mi := &file_cgf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalFlow) ProtoMessage() {}

func (x *LocalFlow) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalFlow.ProtoReflect.Descriptor instead.
func (*LocalFlow) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{9}
}

func (x *LocalFlow) GetVertices() []*FlowVertex {
	if x != nil {
		return x.Vertices
	}
	return nil
}

func (x *LocalFlow) GetEdges() []*FlowEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *LocalFlow) GetCallsites() []*CallSite {
	if x != nil {
		return x.Callsites
	}
	return nil
}

type FlowVertex struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind       VertexKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=panopticode.cgf.VertexKind" json:"kind,omitempty"`
	Index      uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	FieldPath  []uint32               `protobuf:"varint,4,rep,packed,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"` // bounded k=2 field sensitivity; empty = whole
	CallsiteId uint32                 `protobuf:"varint,5,opt,name=callsite_id,json=callsiteId,proto3" json:"callsite_id,omitempty"`     // for CALL_ARG_PORT / CALL_RESULT_PORT
	Sym        []byte                 `protobuf:"bytes,6,opt,name=sym,proto3" json:"sym,omitempty"`                                      // for IN_GLOBAL / OUT_FIELD: heap-cell identity.
	// IN_GLOBAL: global symbol iid. Both kinds
	// (W1F): H(type, field) — one abstract cell
	// shared by every instance of that type.
	// A set sym on OUT_FIELD makes the out-slot
	// Global(sym), not Field(index).
	Type string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"` // static type (source/sink type match in core)
	Span *Span  `protobuf:"bytes,8,opt,name=span,proto3" json:"span,omitempty"`
	// human names for field_path elements (index-aligned; reporting only —
	// identity is field_path: proto field number when tagged, else struct index)
	FieldNames []string `protobuf:"bytes,9,rep,name=field_names,json=fieldNames,proto3" json:"field_names,omitempty"`
	// human name of the heap cell `sym` addresses, e.g. "epool.Pool.incoming".
	// Reporting only — witness renders it as the route hop that crosses the cell,
	// so a heap-mediated chain still opens against source (doc 24 N2).
	SymName string `protobuf:"bytes,10,opt,name=sym_name,json=symName,proto3" json:"sym_name,omitempty"`
	// A16 (doc 30 §6.1) — the type discriminant that narrows an interface-typed
	// heap cell's writer->reader pairings. H("", <go type string>), empty = no
	// constraint (which is every pre-A16 CGF, so the core's filter is inert on
	// them). Emitted only under --heap-slots --heap-iface-narrow.
	//
	//	IN_GLOBAL:  the CONCRETE type the reader asserts the cell's value to
	//	            (`event.EventSrc.(domain.SBPParam)`). The vertex sits on the
	//	            *ssa.TypeAssert result, not on the load, so a raw use of the
	//	            same field in the same function keeps its unconstrained slot.
	//	OUT_FIELD:  the CONCRETE type this write stores into the interface field
	//	            (the *ssa.MakeInterface operand).
	//
	// A pairing is dropped when both are set and differ. Unknown on either side
	// keeps the pairing — the sound direction.
	IfaceType     []byte `protobuf:"bytes,11,opt,name=iface_type,json=ifaceType,proto3" json:"iface_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowVertex) Reset() {
	*x = FlowVertex{}
	mi := &file_cgf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowVertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowVertex) ProtoMessage() {}

func (x *FlowVertex) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowVertex.ProtoReflect.Descriptor instead.
func (*FlowVertex) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{10}
}

func (x *FlowVertex) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FlowVertex) GetKind() VertexKind {
	if x != nil {
		return x.Kind
	}
	return VertexKind_IN_PARAM
}

func (x *FlowVertex) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FlowVertex) GetFieldPath() []uint32 {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

func (x *FlowVertex) GetCallsiteId() uint32 {
	if x != nil {
		return x.CallsiteId
	}
	return 0
}

func (x *FlowVertex) GetSym() []byte {
	if x != nil {
		return x.Sym
	}
	return nil
}

func (x *FlowVertex) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlowVertex) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *FlowVertex) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

func (x *FlowVertex) GetSymName() string {
	if x != nil {
		return x.SymName
	}
	return ""
}

func (x *FlowVertex) GetIfaceType() []byte {
	if x != nil {
		return x.IfaceType
	}
	return nil
}

type FlowEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint32                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            uint32                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	ViaAlias      bool                   `protobuf:"varint,3,opt,name=via_alias,json=viaAlias,proto3" json:"via_alias,omitempty"` // points-to-derived => lower confidence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEdge) Reset() {
	*x = FlowEdge{}
	mi := &file_cgf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEdge) ProtoMessage() {}

func (x *FlowEdge) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEdge.ProtoReflect.Descriptor instead.
func (*FlowEdge) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{11}
}

func (x *FlowEdge) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *FlowEdge) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *FlowEdge) GetViaAlias() bool {
	if x != nil {
		return x.ViaAlias
	}
	return false
}

// ---------------------------------------------------------------------------
// Call sites — the wiring the core needs to compose summaries.
// ---------------------------------------------------------------------------
type CallSite struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind               CallSite_Kind          `protobuf:"varint,2,opt,name=kind,proto3,enum=panopticode.cgf.CallSite_Kind" json:"kind,omitempty"`
	CalleeIids         [][]byte               `protobuf:"bytes,3,rep,name=callee_iids,json=calleeIids,proto3" json:"callee_iids,omitempty"`
	Opaque             bool                   `protobuf:"varint,4,opt,name=opaque,proto3" json:"opaque,omitempty"`                       // unresolved => core applies default leaf
	CalleeFqn          string                 `protobuf:"bytes,5,opt,name=callee_fqn,json=calleeFqn,proto3" json:"callee_fqn,omitempty"` // for catalog fqn/selector matching
	Argc               uint32                 `protobuf:"varint,6,opt,name=argc,proto3" json:"argc,omitempty"`                           // arg-port vertices for 0..argc-1
	Arg0IsReceiver     bool                   `protobuf:"varint,7,opt,name=arg0_is_receiver,json=arg0IsReceiver,proto3" json:"arg0_is_receiver,omitempty"`
	Resultc            uint32                 `protobuf:"varint,8,opt,name=resultc,proto3" json:"resultc,omitempty"` // result-port vertices for 0..resultc-1
	Span               *Span                  `protobuf:"bytes,9,opt,name=span,proto3" json:"span,omitempty"`
	DispatchConfidence float32                `protobuf:"fixed32,10,opt,name=dispatch_confidence,json=dispatchConfidence,proto3" json:"dispatch_confidence,omitempty"` // 1.0 static; <1 VTA fan-out / unresolved
	StreamOp           CallSite_StreamOp      `protobuf:"varint,11,opt,name=stream_op,json=streamOp,proto3,enum=panopticode.cgf.CallSite_StreamOp" json:"stream_op,omitempty"`
	StreamClientSide   bool                   `protobuf:"varint,12,opt,name=stream_client_side,json=streamClientSide,proto3" json:"stream_client_side,omitempty"` // true: op on Svc_MClient; false: on Svc_MServer
	// B1 (doc 31 §4) — bit j set = result j is `error`-typed
	// (types.Implements, so concrete error types count too). The core's default
	// leaf refuses to taint those ports unless the callee is a catalog-listed
	// error wrapper, which is the largest FP class in the tree (doc 30 §6.2).
	//
	// Zero on every pre-B1 CGF, and zero means "unknown" — the core's filter is
	// inert on them, the sound direction. Result-port vertices carry no `type`
	// (flow.go:585 emits ""), which is why this is a fact and not a lookup; a
	// bitmask rather than filling those types keeps it one varint per callsite
	// and inert with respect to any future consumer of `type`.
	// Emitted only under --error-results.
	ErrorResults uint64 `protobuf:"varint,13,opt,name=error_results,json=errorResults,proto3" json:"error_results,omitempty"`
	// Name of arg port i (len == argc, "" = unnamed). Set by frontends whose
	// call convention is by-name (GraphQL operations). Core: normalize.rs
	// rewrites CALL_ARG_PORT indices into the contract's positional frame.
	ArgNames      []string `protobuf:"bytes,14,rep,name=arg_names,json=argNames,proto3" json:"arg_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallSite) Reset() {
	*x = CallSite{}
	mi := &file_cgf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSite) ProtoMessage() {}

func (x *CallSite) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSite.ProtoReflect.Descriptor instead.
func (*CallSite) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{12}
}

func (x *CallSite) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CallSite) GetKind() CallSite_Kind {
	if x != nil {
		return x.Kind
	}
	return CallSite_STATIC
}

func (x *CallSite) GetCalleeIids() [][]byte {
	if x != nil {
		return x.CalleeIids
	}
	return nil
}

func (x *CallSite) GetOpaque() bool {
	if x != nil {
		return x.Opaque
	}
	return false
}

func (x *CallSite) GetCalleeFqn() string {
	if x != nil {
		return x.CalleeFqn
	}
	return ""
}

func (x *CallSite) GetArgc() uint32 {
	if x != nil {
		return x.Argc
	}
	return 0
}

func (x *CallSite) GetArg0IsReceiver() bool {
	if x != nil {
		return x.Arg0IsReceiver
	}
	return false
}

func (x *CallSite) GetResultc() uint32 {
	if x != nil {
		return x.Resultc
	}
	return 0
}

func (x *CallSite) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *CallSite) GetDispatchConfidence() float32 {
	if x != nil {
		return x.DispatchConfidence
	}
	return 0
}

func (x *CallSite) GetStreamOp() CallSite_StreamOp {
	if x != nil {
		return x.StreamOp
	}
	return CallSite_STREAM_OP_NONE
}

func (x *CallSite) GetStreamClientSide() bool {
	if x != nil {
		return x.StreamClientSide
	}
	return false
}

func (x *CallSite) GetErrorResults() uint64 {
	if x != nil {
		return x.ErrorResults
	}
	return 0
}

func (x *CallSite) GetArgNames() []string {
	if x != nil {
		return x.ArgNames
	}
	return nil
}

// ---------------------------------------------------------------------------
// Contract facts — the cross-repo currency (doc 02 §4).
// ---------------------------------------------------------------------------
type ProtoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Fields        []*ProtoField          `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoMessage) Reset() {
	*x = ProtoMessage{}
	mi := &file_cgf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMessage) ProtoMessage() {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMessage.ProtoReflect.Descriptor instead.
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{13}
}

func (x *ProtoMessage) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ProtoMessage) GetFields() []*ProtoField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ProtoField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Pii           []*PiiTag              `protobuf:"bytes,4,rep,name=pii,proto3" json:"pii,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoField) Reset() {
	*x = ProtoField{}
	mi := &file_cgf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoField) ProtoMessage() {}

func (x *ProtoField) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoField.ProtoReflect.Descriptor instead.
func (*ProtoField) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{14}
}

func (x *ProtoField) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ProtoField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtoField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtoField) GetPii() []*PiiTag {
	if x != nil {
		return x.Pii
	}
	return nil
}

type PiiTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PiiTag) Reset() {
	*x = PiiTag{}
	mi := &file_cgf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PiiTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PiiTag) ProtoMessage() {}

func (x *PiiTag) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PiiTag.ProtoReflect.Descriptor instead.
func (*PiiTag) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{15}
}

func (x *PiiTag) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GrpcMethod struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Iid             []byte                 `protobuf:"bytes,1,opt,name=iid,proto3" json:"iid,omitempty"`                           // cross-repo store key
	FullName        string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"` // "ledger.Ledger/GetAccount"
	InputMsg        string                 `protobuf:"bytes,3,opt,name=input_msg,json=inputMsg,proto3" json:"input_msg,omitempty"` // ProtoMessage.full_name
	OutputMsg       string                 `protobuf:"bytes,4,opt,name=output_msg,json=outputMsg,proto3" json:"output_msg,omitempty"`
	HandlerIid      []byte                 `protobuf:"bytes,5,opt,name=handler_iid,json=handlerIid,proto3" json:"handler_iid,omitempty"` // server Function.iid bound via binds_to (same repo)
	EndpointIid     []byte                 `protobuf:"bytes,6,opt,name=endpoint_iid,json=endpointIid,proto3" json:"endpoint_iid,omitempty"`
	ClientStreaming bool                   `protobuf:"varint,7,opt,name=client_streaming,json=clientStreaming,proto3" json:"client_streaming,omitempty"` // mirrors descriptor.proto; bidi = both true
	ServerStreaming bool                   `protobuf:"varint,8,opt,name=server_streaming,json=serverStreaming,proto3" json:"server_streaming,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GrpcMethod) Reset() {
	*x = GrpcMethod{}
	mi := &file_cgf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMethod) ProtoMessage() {}

func (x *GrpcMethod) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMethod.ProtoReflect.Descriptor instead.
func (*GrpcMethod) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{16}
}

func (x *GrpcMethod) GetIid() []byte {
	if x != nil {
		return x.Iid
	}
	return nil
}

func (x *GrpcMethod) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GrpcMethod) GetInputMsg() string {
	if x != nil {
		return x.InputMsg
	}
	return ""
}

func (x *GrpcMethod) GetOutputMsg() string {
	if x != nil {
		return x.OutputMsg
	}
	return ""
}

func (x *GrpcMethod) GetHandlerIid() []byte {
	if x != nil {
		return x.HandlerIid
	}
	return nil
}

func (x *GrpcMethod) GetEndpointIid() []byte {
	if x != nil {
		return x.EndpointIid
	}
	return nil
}

func (x *GrpcMethod) GetClientStreaming() bool {
	if x != nil {
		return x.ClientStreaming
	}
	return false
}

func (x *GrpcMethod) GetServerStreaming() bool {
	if x != nil {
		return x.ServerStreaming
	}
	return false
}

type GraphqlField struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Iid         []byte                 `protobuf:"bytes,1,opt,name=iid,proto3" json:"iid,omitempty"`
	TypeField   string                 `protobuf:"bytes,2,opt,name=type_field,json=typeField,proto3" json:"type_field,omitempty"`       // SDL-exact "Account.details", "AuthMutations.login"
	ResolverIid []byte                 `protobuf:"bytes,3,opt,name=resolver_iid,json=resolverIid,proto3" json:"resolver_iid,omitempty"` // gqlgen generated resolver map (exact)
	EndpointIid []byte                 `protobuf:"bytes,4,opt,name=endpoint_iid,json=endpointIid,proto3" json:"endpoint_iid,omitempty"`
	// SDL arg name -> resolver InParam index (flow numbering, ctx = 0). Order is
	// the SDL/generated-dispatch argument order; the core uses it to normalize a
	// by-name client callsite (CallSite.arg_names) into positions (doc 36 §3).
	Args          []*GraphqlArg `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphqlField) Reset() {
	*x = GraphqlField{}
	mi := &file_cgf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphqlField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlField) ProtoMessage() {}

func (x *GraphqlField) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlField.ProtoReflect.Descriptor instead.
func (*GraphqlField) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{17}
}

func (x *GraphqlField) GetIid() []byte {
	if x != nil {
		return x.Iid
	}
	return nil
}

func (x *GraphqlField) GetTypeField() string {
	if x != nil {
		return x.TypeField
	}
	return ""
}

func (x *GraphqlField) GetResolverIid() []byte {
	if x != nil {
		return x.ResolverIid
	}
	return nil
}

func (x *GraphqlField) GetEndpointIid() []byte {
	if x != nil {
		return x.EndpointIid
	}
	return nil
}

func (x *GraphqlField) GetArgs() []*GraphqlArg {
	if x != nil {
		return x.Args
	}
	return nil
}

type GraphqlArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParamIdx      uint32                 `protobuf:"varint,2,opt,name=param_idx,json=paramIdx,proto3" json:"param_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphqlArg) Reset() {
	*x = GraphqlArg{}
	mi := &file_cgf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphqlArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlArg) ProtoMessage() {}

func (x *GraphqlArg) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlArg.ProtoReflect.Descriptor instead.
func (*GraphqlArg) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{18}
}

func (x *GraphqlArg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphqlArg) GetParamIdx() uint32 {
	if x != nil {
		return x.ParamIdx
	}
	return 0
}

// Unifier over GrpcMethod/GraphqlField/HTTPRoute.
type Endpoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Iid            []byte                 `protobuf:"bytes,1,opt,name=iid,proto3" json:"iid,omitempty"`
	Kind           Endpoint_Kind          `protobuf:"varint,2,opt,name=kind,proto3,enum=panopticode.cgf.Endpoint_Kind" json:"kind,omitempty"`
	UntrustedInput bool                   `protobuf:"varint,3,opt,name=untrusted_input,json=untrustedInput,proto3" json:"untrusted_input,omitempty"` // catalog: is this a taint source surface?
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                            // display, e.g. "ledger.Ledger/GetAccount" or "Account.details"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_cgf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_cgf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_cgf_proto_rawDescGZIP(), []int{19}
}

func (x *Endpoint) GetIid() []byte {
	if x != nil {
		return x.Iid
	}
	return nil
}

func (x *Endpoint) GetKind() Endpoint_Kind {
	if x != nil {
		return x.Kind
	}
	return Endpoint_GRPC
}

func (x *Endpoint) GetUntrustedInput() bool {
	if x != nil {
		return x.UntrustedInput
	}
	return false
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_cgf_proto protoreflect.FileDescriptor

const file_cgf_proto_rawDesc = "" +
	"\n" +
	"\tcgf.proto\x12\x0fpanopticode.cgf\"\x90\x04\n" +
	"\n" +
	"CgfPackage\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x12!\n" +
	"\fpackage_path\x18\x03 \x01(\tR\vpackagePath\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\x05R\rschemaVersion\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x127\n" +
	"\tfunctions\x18\n" +
	" \x03(\v2\x19.panopticode.cgf.FunctionR\tfunctions\x12+\n" +
	"\x05types\x18\v \x03(\v2\x15.panopticode.cgf.TypeR\x05types\x12D\n" +
	"\x0eproto_messages\x18\f \x03(\v2\x1d.panopticode.cgf.ProtoMessageR\rprotoMessages\x12>\n" +
	"\fgrpc_methods\x18\r \x03(\v2\x1b.panopticode.cgf.GrpcMethodR\vgrpcMethods\x12D\n" +
	"\x0egraphql_fields\x18\x0e \x03(\v2\x1d.panopticode.cgf.GraphqlFieldR\rgraphqlFields\x127\n" +
	"\tendpoints\x18\x0f \x03(\v2\x19.panopticode.cgf.EndpointR\tendpoints\"+\n" +
	"\x05Ident\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\fR\x03iid\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\fR\x03bid\"@\n" +
	"\x04Span\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x10\n" +
	"\x03col\x18\x03 \x01(\x05R\x03col\"\xd7\x03\n" +
	"\bFunction\x12&\n" +
	"\x02id\x18\x01 \x01(\v2\x16.panopticode.cgf.IdentR\x02id\x12\x10\n" +
	"\x03fqn\x18\x02 \x01(\tR\x03fqn\x12\x18\n" +
	"\apackage\x18\x03 \x01(\tR\apackage\x12/\n" +
	"\x06origin\x18\x04 \x01(\x0e2\x17.panopticode.cgf.OriginR\x06origin\x12\x1c\n" +
	"\tgenerated\x18\x05 \x01(\bR\tgenerated\x128\n" +
	"\tgenerator\x18\x06 \x01(\x0e2\x1a.panopticode.cgf.GeneratorR\tgenerator\x12\x19\n" +
	"\bhas_body\x18\a \x01(\bR\ahasBody\x12)\n" +
	"\x04span\x18\b \x01(\v2\x15.panopticode.cgf.SpanR\x04span\x128\n" +
	"\tsignature\x18\t \x01(\v2\x1a.panopticode.cgf.SignatureR\tsignature\x12.\n" +
	"\x04flow\x18\n" +
	" \x01(\v2\x1a.panopticode.cgf.LocalFlowR\x04flow\x12\x19\n" +
	"\bbinds_to\x18\v \x03(\fR\abindsTo\x12#\n" +
	"\rsource_params\x18\f \x03(\rR\fsourceParams\"\xae\x01\n" +
	"\tSignature\x12.\n" +
	"\x06params\x18\x01 \x03(\v2\x16.panopticode.cgf.ParamR\x06params\x12!\n" +
	"\fhas_receiver\x18\x02 \x01(\bR\vhasReceiver\x122\n" +
	"\areturns\x18\x03 \x03(\v2\x18.panopticode.cgf.TypeRefR\areturns\x12\x1a\n" +
	"\bvariadic\x18\x04 \x01(\bR\bvariadic\"F\n" +
	"\x05Param\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x15\n" +
	"\x06by_ref\x18\x03 \x01(\bR\x05byRef\"\x1d\n" +
	"\aTypeRef\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\xc6\x01\n" +
	"\x04Type\x12\x10\n" +
	"\x03fqn\x18\x01 \x01(\tR\x03fqn\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.panopticode.cgf.Type.KindR\x04kind\x12\x1e\n" +
	"\n" +
	"implements\x18\x03 \x03(\fR\n" +
	"implements\x12.\n" +
	"\x06fields\x18\x04 \x03(\v2\x16.panopticode.cgf.FieldR\x06fields\",\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06STRUCT\x10\x00\x12\r\n" +
	"\tINTERFACE\x10\x01\x12\t\n" +
	"\x05ALIAS\x10\x02\"E\n" +
	"\x05Field\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xae\x01\n" +
	"\tLocalFlow\x127\n" +
	"\bvertices\x18\x01 \x03(\v2\x1b.panopticode.cgf.FlowVertexR\bvertices\x12/\n" +
	"\x05edges\x18\x02 \x03(\v2\x19.panopticode.cgf.FlowEdgeR\x05edges\x127\n" +
	"\tcallsites\x18\x03 \x03(\v2\x19.panopticode.cgf.CallSiteR\tcallsites\"\xcf\x02\n" +
	"\n" +
	"FlowVertex\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.panopticode.cgf.VertexKindR\x04kind\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12\x1d\n" +
	"\n" +
	"field_path\x18\x04 \x03(\rR\tfieldPath\x12\x1f\n" +
	"\vcallsite_id\x18\x05 \x01(\rR\n" +
	"callsiteId\x12\x10\n" +
	"\x03sym\x18\x06 \x01(\fR\x03sym\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12)\n" +
	"\x04span\x18\b \x01(\v2\x15.panopticode.cgf.SpanR\x04span\x12\x1f\n" +
	"\vfield_names\x18\t \x03(\tR\n" +
	"fieldNames\x12\x19\n" +
	"\bsym_name\x18\n" +
	" \x01(\tR\asymName\x12\x1d\n" +
	"\n" +
	"iface_type\x18\v \x01(\fR\tifaceType\"K\n" +
	"\bFlowEdge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\rR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\rR\x02to\x12\x1b\n" +
	"\tvia_alias\x18\x03 \x01(\bR\bviaAlias\"\xa8\x05\n" +
	"\bCallSite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x122\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1e.panopticode.cgf.CallSite.KindR\x04kind\x12\x1f\n" +
	"\vcallee_iids\x18\x03 \x03(\fR\n" +
	"calleeIids\x12\x16\n" +
	"\x06opaque\x18\x04 \x01(\bR\x06opaque\x12\x1d\n" +
	"\n" +
	"callee_fqn\x18\x05 \x01(\tR\tcalleeFqn\x12\x12\n" +
	"\x04argc\x18\x06 \x01(\rR\x04argc\x12(\n" +
	"\x10arg0_is_receiver\x18\a \x01(\bR\x0earg0IsReceiver\x12\x18\n" +
	"\aresultc\x18\b \x01(\rR\aresultc\x12)\n" +
	"\x04span\x18\t \x01(\v2\x15.panopticode.cgf.SpanR\x04span\x12/\n" +
	"\x13dispatch_confidence\x18\n" +
	" \x01(\x02R\x12dispatchConfidence\x12?\n" +
	"\tstream_op\x18\v \x01(\x0e2\".panopticode.cgf.CallSite.StreamOpR\bstreamOp\x12,\n" +
	"\x12stream_client_side\x18\f \x01(\bR\x10streamClientSide\x12#\n" +
	"\rerror_results\x18\r \x01(\x04R\ferrorResults\x12\x1b\n" +
	"\targ_names\x18\x0e \x03(\tR\bargNames\"S\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06STATIC\x10\x00\x12\v\n" +
	"\aVIRTUAL\x10\x01\x12\x12\n" +
	"\x0eINVOKES_REMOTE\x10\x02\x12\x06\n" +
	"\x02GO\x10\x03\x12\t\n" +
	"\x05DEFER\x10\x04\x12\v\n" +
	"\aBUILTIN\x10\x05\"F\n" +
	"\bStreamOp\x12\x12\n" +
	"\x0eSTREAM_OP_NONE\x10\x00\x12\x12\n" +
	"\x0eSTREAM_OP_SEND\x10\x01\x12\x12\n" +
	"\x0eSTREAM_OP_RECV\x10\x02\"`\n" +
	"\fProtoMessage\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x123\n" +
	"\x06fields\x18\x02 \x03(\v2\x1b.panopticode.cgf.ProtoFieldR\x06fields\"u\n" +
	"\n" +
	"ProtoField\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12)\n" +
	"\x03pii\x18\x04 \x03(\v2\x17.panopticode.cgf.PiiTagR\x03pii\"$\n" +
	"\x06PiiTag\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"\x91\x02\n" +
	"\n" +
	"GrpcMethod\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\fR\x03iid\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1b\n" +
	"\tinput_msg\x18\x03 \x01(\tR\binputMsg\x12\x1d\n" +
	"\n" +
	"output_msg\x18\x04 \x01(\tR\toutputMsg\x12\x1f\n" +
	"\vhandler_iid\x18\x05 \x01(\fR\n" +
	"handlerIid\x12!\n" +
	"\fendpoint_iid\x18\x06 \x01(\fR\vendpointIid\x12)\n" +
	"\x10client_streaming\x18\a \x01(\bR\x0fclientStreaming\x12)\n" +
	"\x10server_streaming\x18\b \x01(\bR\x0fserverStreaming\"\xb6\x01\n" +
	"\fGraphqlField\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\fR\x03iid\x12\x1d\n" +
	"\n" +
	"type_field\x18\x02 \x01(\tR\ttypeField\x12!\n" +
	"\fresolver_iid\x18\x03 \x01(\fR\vresolverIid\x12!\n" +
	"\fendpoint_iid\x18\x04 \x01(\fR\vendpointIid\x12/\n" +
	"\x04args\x18\x05 \x03(\v2\x1b.panopticode.cgf.GraphqlArgR\x04args\"=\n" +
	"\n" +
	"GraphqlArg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tparam_idx\x18\x02 \x01(\rR\bparamIdx\"\xb6\x01\n" +
	"\bEndpoint\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\fR\x03iid\x122\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1e.panopticode.cgf.Endpoint.KindR\x04kind\x12'\n" +
	"\x0funtrusted_input\x18\x03 \x01(\bR\x0euntrustedInput\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"'\n" +
	"\x04Kind\x12\b\n" +
	"\x04GRPC\x10\x00\x12\v\n" +
	"\aGRAPHQL\x10\x01\x12\b\n" +
	"\x04HTTP\x10\x02*<\n" +
	"\x06Origin\x12\x0f\n" +
	"\vORIGIN_USER\x10\x00\x12\x11\n" +
	"\rORIGIN_STDLIB\x10\x01\x12\x0e\n" +
	"\n" +
	"ORIGIN_DEP\x10\x02*J\n" +
	"\tGenerator\x12\f\n" +
	"\bGEN_NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"GEN_PROTOC\x10\x01\x12\x0e\n" +
	"\n" +
	"GEN_GQLGEN\x10\x02\x12\x0f\n" +
	"\vGEN_MOCKGEN\x10\x03*\xaf\x01\n" +
	"\n" +
	"VertexKind\x12\f\n" +
	"\bIN_PARAM\x10\x00\x12\x0f\n" +
	"\vIN_RECEIVER\x10\x01\x12\r\n" +
	"\tIN_GLOBAL\x10\x02\x12\x0e\n" +
	"\n" +
	"OUT_RETURN\x10\x03\x12\x13\n" +
	"\x0fOUT_PARAM_BYREF\x10\x04\x12\r\n" +
	"\tOUT_FIELD\x10\x05\x12\x11\n" +
	"\rCALL_ARG_PORT\x10\x06\x12\x14\n" +
	"\x10CALL_RESULT_PORT\x10\a\x12\x16\n" +
	"\x12OUT_RECEIVER_BYREF\x10\bB9Z7github.com/panoptiorg/panoptife-go/internal/cgfpb;cgfpbb\x06proto3"

var (
	file_cgf_proto_rawDescOnce sync.Once
	file_cgf_proto_rawDescData []byte
)

func file_cgf_proto_rawDescGZIP() []byte {
	file_cgf_proto_rawDescOnce.Do(func() {
		file_cgf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cgf_proto_rawDesc), len(file_cgf_proto_rawDesc)))
	})
	return file_cgf_proto_rawDescData
}

var file_cgf_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_cgf_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_cgf_proto_goTypes = []any{
	(Origin)(0),            // 0: panopticode.cgf.Origin
	(Generator)(0),         // 1: panopticode.cgf.Generator
	(VertexKind)(0),        // 2: panopticode.cgf.VertexKind
	(Type_Kind)(0),         // 3: panopticode.cgf.Type.Kind
	(CallSite_Kind)(0),     // 4: panopticode.cgf.CallSite.Kind
	(CallSite_StreamOp)(0), // 5: panopticode.cgf.CallSite.StreamOp
	(Endpoint_Kind)(0),     // 6: panopticode.cgf.Endpoint.Kind
	(*CgfPackage)(nil),     // 7: panopticode.cgf.CgfPackage
	(*Ident)(nil),          // 8: panopticode.cgf.Ident
	(*Span)(nil),           // 9: panopticode.cgf.Span
	(*Function)(nil),       // 10: panopticode.cgf.Function
	(*Signature)(nil),      // 11: panopticode.cgf.Signature
	(*Param)(nil),          // 12: panopticode.cgf.Param
	(*TypeRef)(nil),        // 13: panopticode.cgf.TypeRef
	(*Type)(nil),           // 14: panopticode.cgf.Type
	(*Field)(nil),          // 15: panopticode.cgf.Field
	(*LocalFlow)(nil),      // 16: panopticode.cgf.LocalFlow
	(*FlowVertex)(nil),     // 17: panopticode.cgf.FlowVertex
	(*FlowEdge)(nil),       // 18: panopticode.cgf.FlowEdge
	(*CallSite)(nil),       // 19: panopticode.cgf.CallSite
	(*ProtoMessage)(nil),   // 20: panopticode.cgf.ProtoMessage
	(*ProtoField)(nil),     // 21: panopticode.cgf.ProtoField
	(*PiiTag)(nil),         // 22: panopticode.cgf.PiiTag
	(*GrpcMethod)(nil),     // 23: panopticode.cgf.GrpcMethod
	(*GraphqlField)(nil),   // 24: panopticode.cgf.GraphqlField
	(*GraphqlArg)(nil),     // 25: panopticode.cgf.GraphqlArg
	(*Endpoint)(nil),       // 26: panopticode.cgf.Endpoint
}
var file_cgf_proto_depIdxs = []int32{
	10, // 0: panopticode.cgf.CgfPackage.functions:type_name -> panopticode.cgf.Function
	14, // 1: panopticode.cgf.CgfPackage.types:type_name -> panopticode.cgf.Type
	20, // 2: panopticode.cgf.CgfPackage.proto_messages:type_name -> panopticode.cgf.ProtoMessage
	23, // 3: panopticode.cgf.CgfPackage.grpc_methods:type_name -> panopticode.cgf.GrpcMethod
	24, // 4: panopticode.cgf.CgfPackage.graphql_fields:type_name -> panopticode.cgf.GraphqlField
	26, // 5: panopticode.cgf.CgfPackage.endpoints:type_name -> panopticode.cgf.Endpoint
	8,  // 6: panopticode.cgf.Function.id:type_name -> panopticode.cgf.Ident
	0,  // 7: panopticode.cgf.Function.origin:type_name -> panopticode.cgf.Origin
	1,  // 8: panopticode.cgf.Function.generator:type_name -> panopticode.cgf.Generator
	9,  // 9: panopticode.cgf.Function.span:type_name -> panopticode.cgf.Span
	11, // 10: panopticode.cgf.Function.signature:type_name -> panopticode.cgf.Signature
	16, // 11: panopticode.cgf.Function.flow:type_name -> panopticode.cgf.LocalFlow
	12, // 12: panopticode.cgf.Signature.params:type_name -> panopticode.cgf.Param
	13, // 13: panopticode.cgf.Signature.returns:type_name -> panopticode.cgf.TypeRef
	3,  // 14: panopticode.cgf.Type.kind:type_name -> panopticode.cgf.Type.Kind
	15, // 15: panopticode.cgf.Type.fields:type_name -> panopticode.cgf.Field
	17, // 16: panopticode.cgf.LocalFlow.vertices:type_name -> panopticode.cgf.FlowVertex
	18, // 17: panopticode.cgf.LocalFlow.edges:type_name -> panopticode.cgf.FlowEdge
	19, // 18: panopticode.cgf.LocalFlow.callsites:type_name -> panopticode.cgf.CallSite
	2,  // 19: panopticode.cgf.FlowVertex.kind:type_name -> panopticode.cgf.VertexKind
	9,  // 20: panopticode.cgf.FlowVertex.span:type_name -> panopticode.cgf.Span
	4,  // 21: panopticode.cgf.CallSite.kind:type_name -> panopticode.cgf.CallSite.Kind
	9,  // 22: panopticode.cgf.CallSite.span:type_name -> panopticode.cgf.Span
	5,  // 23: panopticode.cgf.CallSite.stream_op:type_name -> panopticode.cgf.CallSite.StreamOp
	21, // 24: panopticode.cgf.ProtoMessage.fields:type_name -> panopticode.cgf.ProtoField
	22, // 25: panopticode.cgf.ProtoField.pii:type_name -> panopticode.cgf.PiiTag
	25, // 26: panopticode.cgf.GraphqlField.args:type_name -> panopticode.cgf.GraphqlArg
	6,  // 27: panopticode.cgf.Endpoint.kind:type_name -> panopticode.cgf.Endpoint.Kind
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_cgf_proto_init() }
func file_cgf_proto_init() {
	if File_cgf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cgf_proto_rawDesc), len(file_cgf_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cgf_proto_goTypes,
		DependencyIndexes: file_cgf_proto_depIdxs,
		EnumInfos:         file_cgf_proto_enumTypes,
		MessageInfos:      file_cgf_proto_msgTypes,
	}.Build()
	File_cgf_proto = out.File
	file_cgf_proto_goTypes = nil
	file_cgf_proto_depIdxs = nil
}
