// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: summary.proto

// Summary — the IFDS procedure summary (the jump function) and the cross-repo
// contract wire format. Content-addressed by summary_key. See docs/04.

package summarypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mirror of cgf.VertexKind (kept independent so summary.proto stands alone).
type SlotKind int32

const (
	SlotKind_SLOT_IN_PARAM        SlotKind = 0
	SlotKind_SLOT_IN_RECEIVER     SlotKind = 1
	SlotKind_SLOT_IN_GLOBAL       SlotKind = 2
	SlotKind_SLOT_OUT_RETURN      SlotKind = 3
	SlotKind_SLOT_OUT_PARAM_BYREF SlotKind = 4
	SlotKind_SLOT_OUT_FIELD       SlotKind = 5
	SlotKind_SLOT_SINK_CALL       SlotKind = 6 // terminal sink position
	SlotKind_SLOT_STREAM_IN       SlotKind = 7 // data arriving from the peer over a gRPC stream
	SlotKind_SLOT_STREAM_OUT      SlotKind = 8 // data sent to the peer over a gRPC stream
)

// Enum value maps for SlotKind.
var (
	SlotKind_name = map[int32]string{
		0: "SLOT_IN_PARAM",
		1: "SLOT_IN_RECEIVER",
		2: "SLOT_IN_GLOBAL",
		3: "SLOT_OUT_RETURN",
		4: "SLOT_OUT_PARAM_BYREF",
		5: "SLOT_OUT_FIELD",
		6: "SLOT_SINK_CALL",
		7: "SLOT_STREAM_IN",
		8: "SLOT_STREAM_OUT",
	}
	SlotKind_value = map[string]int32{
		"SLOT_IN_PARAM":        0,
		"SLOT_IN_RECEIVER":     1,
		"SLOT_IN_GLOBAL":       2,
		"SLOT_OUT_RETURN":      3,
		"SLOT_OUT_PARAM_BYREF": 4,
		"SLOT_OUT_FIELD":       5,
		"SLOT_SINK_CALL":       6,
		"SLOT_STREAM_IN":       7,
		"SLOT_STREAM_OUT":      8,
	}
)

func (x SlotKind) Enum() *SlotKind {
	p := new(SlotKind)
	*p = x
	return p
}

func (x SlotKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotKind) Descriptor() protoreflect.EnumDescriptor {
	return file_summary_proto_enumTypes[0].Descriptor()
}

func (SlotKind) Type() protoreflect.EnumType {
	return &file_summary_proto_enumTypes[0]
}

func (x SlotKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotKind.Descriptor instead.
func (SlotKind) EnumDescriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{0}
}

type Provenance int32

const (
	Provenance_PROV_ANALYZED Provenance = 0 // computed from real body
	Provenance_PROV_INFERRED Provenance = 1 // heuristic / cross-repo cycle break
	Provenance_PROV_DEFAULT  Provenance = 2 // conservative default leaf (missing contract)
	Provenance_PROV_OPAQUE   Provenance = 3 // unresolved callee
)

// Enum value maps for Provenance.
var (
	Provenance_name = map[int32]string{
		0: "PROV_ANALYZED",
		1: "PROV_INFERRED",
		2: "PROV_DEFAULT",
		3: "PROV_OPAQUE",
	}
	Provenance_value = map[string]int32{
		"PROV_ANALYZED": 0,
		"PROV_INFERRED": 1,
		"PROV_DEFAULT":  2,
		"PROV_OPAQUE":   3,
	}
)

func (x Provenance) Enum() *Provenance {
	p := new(Provenance)
	*p = x
	return p
}

func (x Provenance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provenance) Descriptor() protoreflect.EnumDescriptor {
	return file_summary_proto_enumTypes[1].Descriptor()
}

func (Provenance) Type() protoreflect.EnumType {
	return &file_summary_proto_enumTypes[1]
}

func (x Provenance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provenance.Descriptor instead.
func (Provenance) EnumDescriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{1}
}

type SlotRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SlotKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=panopticode.summary.SlotKind" json:"kind,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	FieldPath     []uint32               `protobuf:"varint,3,rep,packed,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Sym           []byte                 `protobuf:"bytes,4,opt,name=sym,proto3" json:"sym,omitempty"` // for globals
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotRef) Reset() {
	*x = SlotRef{}
	mi := &file_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotRef) ProtoMessage() {}

func (x *SlotRef) ProtoReflect() protoreflect.Message {
	mi := &file_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotRef.ProtoReflect.Descriptor instead.
func (*SlotRef) Descriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{0}
}

func (x *SlotRef) GetKind() SlotKind {
	if x != nil {
		return x.Kind
	}
	return SlotKind_SLOT_IN_PARAM
}

func (x *SlotRef) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SlotRef) GetFieldPath() []uint32 {
	if x != nil {
		return x.FieldPath
	}
	return nil
}

func (x *SlotRef) GetSym() []byte {
	if x != nil {
		return x.Sym
	}
	return nil
}

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Col           int32                  `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_summary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_summary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{1}
}

func (x *Span) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Span) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Span) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type TaintFlow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InSlot        *SlotRef               `protobuf:"bytes,1,opt,name=in_slot,json=inSlot,proto3" json:"in_slot,omitempty"`
	OutSlot       *SlotRef               `protobuf:"bytes,2,opt,name=out_slot,json=outSlot,proto3" json:"out_slot,omitempty"`
	LabelSet      uint64                 `protobuf:"varint,3,opt,name=label_set,json=labelSet,proto3" json:"label_set,omitempty"` // MVP: bit 0 = tainted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaintFlow) Reset() {
	*x = TaintFlow{}
	mi := &file_summary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaintFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaintFlow) ProtoMessage() {}

func (x *TaintFlow) ProtoReflect() protoreflect.Message {
	mi := &file_summary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaintFlow.ProtoReflect.Descriptor instead.
func (*TaintFlow) Descriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{2}
}

func (x *TaintFlow) GetInSlot() *SlotRef {
	if x != nil {
		return x.InSlot
	}
	return nil
}

func (x *TaintFlow) GetOutSlot() *SlotRef {
	if x != nil {
		return x.OutSlot
	}
	return nil
}

func (x *TaintFlow) GetLabelSet() uint64 {
	if x != nil {
		return x.LabelSet
	}
	return 0
}

type Sanitized struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *SlotRef               `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	SanitizerKind string                 `protobuf:"bytes,2,opt,name=sanitizer_kind,json=sanitizerKind,proto3" json:"sanitizer_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sanitized) Reset() {
	*x = Sanitized{}
	mi := &file_summary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sanitized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sanitized) ProtoMessage() {}

func (x *Sanitized) ProtoReflect() protoreflect.Message {
	mi := &file_summary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sanitized.ProtoReflect.Descriptor instead.
func (*Sanitized) Descriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{3}
}

func (x *Sanitized) GetSlot() *SlotRef {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *Sanitized) GetSanitizerKind() string {
	if x != nil {
		return x.SanitizerKind
	}
	return ""
}

type SinkHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InSlot        *SlotRef               `protobuf:"bytes,1,opt,name=in_slot,json=inSlot,proto3" json:"in_slot,omitempty"`
	SinkClass     string                 `protobuf:"bytes,2,opt,name=sink_class,json=sinkClass,proto3" json:"sink_class,omitempty"` // "sqli" | "log" | "exec" | "egress" | ...
	Span          *Span                  `protobuf:"bytes,3,opt,name=span,proto3" json:"span,omitempty"`
	CrossBoundary bool                   `protobuf:"varint,4,opt,name=cross_boundary,json=crossBoundary,proto3" json:"cross_boundary,omitempty"` // hop crossed a service boundary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkHit) Reset() {
	*x = SinkHit{}
	mi := &file_summary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkHit) ProtoMessage() {}

func (x *SinkHit) ProtoReflect() protoreflect.Message {
	mi := &file_summary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkHit.ProtoReflect.Descriptor instead.
func (*SinkHit) Descriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{4}
}

func (x *SinkHit) GetInSlot() *SlotRef {
	if x != nil {
		return x.InSlot
	}
	return nil
}

func (x *SinkHit) GetSinkClass() string {
	if x != nil {
		return x.SinkClass
	}
	return ""
}

func (x *SinkHit) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *SinkHit) GetCrossBoundary() bool {
	if x != nil {
		return x.CrossBoundary
	}
	return false
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FnIid         []byte                 `protobuf:"bytes,1,opt,name=fn_iid,json=fnIid,proto3" json:"fn_iid,omitempty"`
	Bid           []byte                 `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`                                       // structural body key
	SummaryKey    []byte                 `protobuf:"bytes,3,opt,name=summary_key,json=summaryKey,proto3" json:"summary_key,omitempty"`       // hash(bid + sorted[callee.contract_hash]) — cache key
	ContractHash  []byte                 `protobuf:"bytes,4,opt,name=contract_hash,json=contractHash,proto3" json:"contract_hash,omitempty"` // behavior-only; drives caller cutoff + cross-repo diff
	Flows         []*TaintFlow           `protobuf:"bytes,5,rep,name=flows,proto3" json:"flows,omitempty"`
	Sanitized     []*Sanitized           `protobuf:"bytes,6,rep,name=sanitized,proto3" json:"sanitized,omitempty"`
	SinkHits      []*SinkHit             `protobuf:"bytes,7,rep,name=sink_hits,json=sinkHits,proto3" json:"sink_hits,omitempty"`
	Confidence    float32                `protobuf:"fixed32,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Provenance    Provenance             `protobuf:"varint,9,opt,name=provenance,proto3,enum=panopticode.summary.Provenance" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_summary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_summary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{5}
}

func (x *Summary) GetFnIid() []byte {
	if x != nil {
		return x.FnIid
	}
	return nil
}

func (x *Summary) GetBid() []byte {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *Summary) GetSummaryKey() []byte {
	if x != nil {
		return x.SummaryKey
	}
	return nil
}

func (x *Summary) GetContractHash() []byte {
	if x != nil {
		return x.ContractHash
	}
	return nil
}

func (x *Summary) GetFlows() []*TaintFlow {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *Summary) GetSanitized() []*Sanitized {
	if x != nil {
		return x.Sanitized
	}
	return nil
}

func (x *Summary) GetSinkHits() []*SinkHit {
	if x != nil {
		return x.SinkHits
	}
	return nil
}

func (x *Summary) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Summary) GetProvenance() Provenance {
	if x != nil {
		return x.Provenance
	}
	return Provenance_PROV_ANALYZED
}

// A published cross-repo contract bundle: one repo's public endpoint summaries.
type ContractBundle struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Repo      string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	CommitSha string                 `protobuf:"bytes,2,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	// GrpcMethod.iid (hex) -> handler Summary
	EndpointSummaries map[string]*Summary `protobuf:"bytes,3,rep,name=endpoint_summaries,json=endpointSummaries,proto3" json:"endpoint_summaries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContractBundle) Reset() {
	*x = ContractBundle{}
	mi := &file_summary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractBundle) ProtoMessage() {}

func (x *ContractBundle) ProtoReflect() protoreflect.Message {
	mi := &file_summary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractBundle.ProtoReflect.Descriptor instead.
func (*ContractBundle) Descriptor() ([]byte, []int) {
	return file_summary_proto_rawDescGZIP(), []int{6}
}

func (x *ContractBundle) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ContractBundle) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *ContractBundle) GetEndpointSummaries() map[string]*Summary {
	if x != nil {
		return x.EndpointSummaries
	}
	return nil
}

var File_summary_proto protoreflect.FileDescriptor

const file_summary_proto_rawDesc = "" +
	"\n" +
	"\rsummary.proto\x12\x13panopticode.summary\"\x83\x01\n" +
	"\aSlotRef\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.panopticode.summary.SlotKindR\x04kind\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x1d\n" +
	"\n" +
	"field_path\x18\x03 \x03(\rR\tfieldPath\x12\x10\n" +
	"\x03sym\x18\x04 \x01(\fR\x03sym\"@\n" +
	"\x04Span\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x12\x10\n" +
	"\x03col\x18\x03 \x01(\x05R\x03col\"\x98\x01\n" +
	"\tTaintFlow\x125\n" +
	"\ain_slot\x18\x01 \x01(\v2\x1c.panopticode.summary.SlotRefR\x06inSlot\x127\n" +
	"\bout_slot\x18\x02 \x01(\v2\x1c.panopticode.summary.SlotRefR\aoutSlot\x12\x1b\n" +
	"\tlabel_set\x18\x03 \x01(\x04R\blabelSet\"d\n" +
	"\tSanitized\x120\n" +
	"\x04slot\x18\x01 \x01(\v2\x1c.panopticode.summary.SlotRefR\x04slot\x12%\n" +
	"\x0esanitizer_kind\x18\x02 \x01(\tR\rsanitizerKind\"\xb5\x01\n" +
	"\aSinkHit\x125\n" +
	"\ain_slot\x18\x01 \x01(\v2\x1c.panopticode.summary.SlotRefR\x06inSlot\x12\x1d\n" +
	"\n" +
	"sink_class\x18\x02 \x01(\tR\tsinkClass\x12-\n" +
	"\x04span\x18\x03 \x01(\v2\x19.panopticode.summary.SpanR\x04span\x12%\n" +
	"\x0ecross_boundary\x18\x04 \x01(\bR\rcrossBoundary\"\x88\x03\n" +
	"\aSummary\x12\x15\n" +
	"\x06fn_iid\x18\x01 \x01(\fR\x05fnIid\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\fR\x03bid\x12\x1f\n" +
	"\vsummary_key\x18\x03 \x01(\fR\n" +
	"summaryKey\x12#\n" +
	"\rcontract_hash\x18\x04 \x01(\fR\fcontractHash\x124\n" +
	"\x05flows\x18\x05 \x03(\v2\x1e.panopticode.summary.TaintFlowR\x05flows\x12<\n" +
	"\tsanitized\x18\x06 \x03(\v2\x1e.panopticode.summary.SanitizedR\tsanitized\x129\n" +
	"\tsink_hits\x18\a \x03(\v2\x1c.panopticode.summary.SinkHitR\bsinkHits\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x02R\n" +
	"confidence\x12?\n" +
	"\n" +
	"provenance\x18\t \x01(\x0e2\x1f.panopticode.summary.ProvenanceR\n" +
	"provenance\"\x92\x02\n" +
	"\x0eContractBundle\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x02 \x01(\tR\tcommitSha\x12i\n" +
	"\x12endpoint_summaries\x18\x03 \x03(\v2:.panopticode.summary.ContractBundle.EndpointSummariesEntryR\x11endpointSummaries\x1ab\n" +
	"\x16EndpointSummariesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.panopticode.summary.SummaryR\x05value:\x028\x01*\xc7\x01\n" +
	"\bSlotKind\x12\x11\n" +
	"\rSLOT_IN_PARAM\x10\x00\x12\x14\n" +
	"\x10SLOT_IN_RECEIVER\x10\x01\x12\x12\n" +
	"\x0eSLOT_IN_GLOBAL\x10\x02\x12\x13\n" +
	"\x0fSLOT_OUT_RETURN\x10\x03\x12\x18\n" +
	"\x14SLOT_OUT_PARAM_BYREF\x10\x04\x12\x12\n" +
	"\x0eSLOT_OUT_FIELD\x10\x05\x12\x12\n" +
	"\x0eSLOT_SINK_CALL\x10\x06\x12\x12\n" +
	"\x0eSLOT_STREAM_IN\x10\a\x12\x13\n" +
	"\x0fSLOT_STREAM_OUT\x10\b*U\n" +
	"\n" +
	"Provenance\x12\x11\n" +
	"\rPROV_ANALYZED\x10\x00\x12\x11\n" +
	"\rPROV_INFERRED\x10\x01\x12\x10\n" +
	"\fPROV_DEFAULT\x10\x02\x12\x0f\n" +
	"\vPROV_OPAQUE\x10\x03BAZ?github.com/panoptiorg/panoptife-go/internal/summarypb;summarypbb\x06proto3"

var (
	file_summary_proto_rawDescOnce sync.Once
	file_summary_proto_rawDescData []byte
)

func file_summary_proto_rawDescGZIP() []byte {
	file_summary_proto_rawDescOnce.Do(func() {
		file_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_summary_proto_rawDesc), len(file_summary_proto_rawDesc)))
	})
	return file_summary_proto_rawDescData
}

var file_summary_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_summary_proto_goTypes = []any{
	(SlotKind)(0),          // 0: panopticode.summary.SlotKind
	(Provenance)(0),        // 1: panopticode.summary.Provenance
	(*SlotRef)(nil),        // 2: panopticode.summary.SlotRef
	(*Span)(nil),           // 3: panopticode.summary.Span
	(*TaintFlow)(nil),      // 4: panopticode.summary.TaintFlow
	(*Sanitized)(nil),      // 5: panopticode.summary.Sanitized
	(*SinkHit)(nil),        // 6: panopticode.summary.SinkHit
	(*Summary)(nil),        // 7: panopticode.summary.Summary
	(*ContractBundle)(nil), // 8: panopticode.summary.ContractBundle
	nil,                    // 9: panopticode.summary.ContractBundle.EndpointSummariesEntry
}
var file_summary_proto_depIdxs = []int32{
	0,  // 0: panopticode.summary.SlotRef.kind:type_name -> panopticode.summary.SlotKind
	2,  // 1: panopticode.summary.TaintFlow.in_slot:type_name -> panopticode.summary.SlotRef
	2,  // 2: panopticode.summary.TaintFlow.out_slot:type_name -> panopticode.summary.SlotRef
	2,  // 3: panopticode.summary.Sanitized.slot:type_name -> panopticode.summary.SlotRef
	2,  // 4: panopticode.summary.SinkHit.in_slot:type_name -> panopticode.summary.SlotRef
	3,  // 5: panopticode.summary.SinkHit.span:type_name -> panopticode.summary.Span
	4,  // 6: panopticode.summary.Summary.flows:type_name -> panopticode.summary.TaintFlow
	5,  // 7: panopticode.summary.Summary.sanitized:type_name -> panopticode.summary.Sanitized
	6,  // 8: panopticode.summary.Summary.sink_hits:type_name -> panopticode.summary.SinkHit
	1,  // 9: panopticode.summary.Summary.provenance:type_name -> panopticode.summary.Provenance
	9,  // 10: panopticode.summary.ContractBundle.endpoint_summaries:type_name -> panopticode.summary.ContractBundle.EndpointSummariesEntry
	7,  // 11: panopticode.summary.ContractBundle.EndpointSummariesEntry.value:type_name -> panopticode.summary.Summary
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_summary_proto_init() }
func file_summary_proto_init() {
	if File_summary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_summary_proto_rawDesc), len(file_summary_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_summary_proto_goTypes,
		DependencyIndexes: file_summary_proto_depIdxs,
		EnumInfos:         file_summary_proto_enumTypes,
		MessageInfos:      file_summary_proto_msgTypes,
	}.Build()
	File_summary_proto = out.File
	file_summary_proto_goTypes = nil
	file_summary_proto_depIdxs = nil
}
