// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: cgstore.proto

// cgstore — the persisted call-graph snapshot (R4 Ph1, incremental_callgraph_spec
// §4/§8). One Meta + one PkgShard per package, under
// output/cgstore/<repo>/<hex12(storeKey)>/<commit12>/. Go frontend only — the
// Rust core never reads this. Versioned separately from cgf.proto: any breaking
// change bumps schema_version, which is folded into storeKey (old snapshots
// simply miss and a full rebuild rewrites them).

package cgstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Meta is written LAST (after every shard), atomically with the whole snapshot
// dir (temp dir + rename). Its shard list carries per-file content hashes —
// the snapshot's self-check; any mismatch on load ⇒ full rebuild, never guess.
type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"` // module path, e.g. "gitlab.example.com/acme/ledger-svc"
	CommitSha     string                 `protobuf:"bytes,3,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	ParentSha     string                 `protobuf:"bytes,4,opt,name=parent_sha,json=parentSha,proto3" json:"parent_sha,omitempty"`       // first-parent of commit_sha (Ph2 base-graph lookup)
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`                                // resolved scope string (post-expansion)
	PcfeVersion   string                 `protobuf:"bytes,6,opt,name=pcfe_version,json=pcfeVersion,proto3" json:"pcfe_version,omitempty"` // hex sha256 of the running pc-fe binary
	GoToolchain   string                 `protobuf:"bytes,7,opt,name=go_toolchain,json=goToolchain,proto3" json:"go_toolchain,omitempty"` // runtime.Version() of that binary
	CgMode        string                 `protobuf:"bytes,8,opt,name=cg_mode,json=cgMode,proto3" json:"cg_mode,omitempty"`                // "vta" | "cha" — whatever --dispatch built this
	CapN          uint32                 `protobuf:"varint,9,opt,name=cap_n,json=capN,proto3" json:"cap_n,omitempty"`                     // resolver fan-out cap
	ExcludeMocks  bool                   `protobuf:"varint,10,opt,name=exclude_mocks,json=excludeMocks,proto3" json:"exclude_mocks,omitempty"`
	// sha256 over the sorted iids of every emitted function: detects any drift
	// between the snapshot's function universe and a freshly rebuilt SSA that
	// the storeKey inputs failed to capture.
	FnSetHash      []byte `protobuf:"bytes,11,opt,name=fn_set_hash,json=fnSetHash,proto3" json:"fn_set_hash,omitempty"`
	CreatedUnix    int64  `protobuf:"varint,12,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	DispatchWallMs int64  `protobuf:"varint,13,opt,name=dispatch_wall_ms,json=dispatchWallMs,proto3" json:"dispatch_wall_ms,omitempty"` // original graph-build cost (reload reporting)
	// Resolver generics-gap counters, replayed verbatim on the cached path so
	// the `generics-gap:` stderr line stays truthful without a live graph.
	GenericEdges     int32 `protobuf:"varint,14,opt,name=generic_edges,json=genericEdges,proto3" json:"generic_edges,omitempty"`
	SitesAllGeneric  int32 `protobuf:"varint,15,opt,name=sites_all_generic,json=sitesAllGeneric,proto3" json:"sites_all_generic,omitempty"`
	SitesSomeGeneric int32 `protobuf:"varint,16,opt,name=sites_some_generic,json=sitesSomeGeneric,proto3" json:"sites_some_generic,omitempty"`
	// --field-paths at capture time: getter canonicalization drops pb-getter
	// CallSites, so CallSite.Id ordinals only align with a matching-mode
	// enumeration (snapshot.go filters canonicalized calls when true).
	FieldPaths bool `protobuf:"varint,18,opt,name=field_paths,json=fieldPaths,proto3" json:"field_paths,omitempty"`
	// --closure-flow at capture time (W1d). Recorded for the same reason as
	// field_paths: it changes CGF bytes. It does NOT change CallSite.Id alignment
	// — the synthetic binding sites are appended after every real one and
	// n_callsites counts only the real ones — so snapshot.go needs no filter for
	// it. The flag is in the store key regardless, so a snapshot is never
	// replayed under a mode that did not capture it.
	ClosureFlow   bool          `protobuf:"varint,19,opt,name=closure_flow,json=closureFlow,proto3" json:"closure_flow,omitempty"`
	Shards        []*Meta_Shard `protobuf:"bytes,17,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_cgstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_cgstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_cgstore_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Meta) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Meta) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *Meta) GetParentSha() string {
	if x != nil {
		return x.ParentSha
	}
	return ""
}

func (x *Meta) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Meta) GetPcfeVersion() string {
	if x != nil {
		return x.PcfeVersion
	}
	return ""
}

func (x *Meta) GetGoToolchain() string {
	if x != nil {
		return x.GoToolchain
	}
	return ""
}

func (x *Meta) GetCgMode() string {
	if x != nil {
		return x.CgMode
	}
	return ""
}

func (x *Meta) GetCapN() uint32 {
	if x != nil {
		return x.CapN
	}
	return 0
}

func (x *Meta) GetExcludeMocks() bool {
	if x != nil {
		return x.ExcludeMocks
	}
	return false
}

func (x *Meta) GetFnSetHash() []byte {
	if x != nil {
		return x.FnSetHash
	}
	return nil
}

func (x *Meta) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *Meta) GetDispatchWallMs() int64 {
	if x != nil {
		return x.DispatchWallMs
	}
	return 0
}

func (x *Meta) GetGenericEdges() int32 {
	if x != nil {
		return x.GenericEdges
	}
	return 0
}

func (x *Meta) GetSitesAllGeneric() int32 {
	if x != nil {
		return x.SitesAllGeneric
	}
	return 0
}

func (x *Meta) GetSitesSomeGeneric() int32 {
	if x != nil {
		return x.SitesSomeGeneric
	}
	return 0
}

func (x *Meta) GetFieldPaths() bool {
	if x != nil {
		return x.FieldPaths
	}
	return false
}

func (x *Meta) GetClosureFlow() bool {
	if x != nil {
		return x.ClosureFlow
	}
	return false
}

func (x *Meta) GetShards() []*Meta_Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

// PkgShard holds the per-package slice of the snapshot: dispatch edges of the
// callers declared in pkg, plus the satisfaction facts (fingerprints + pairs)
// of the types/interfaces declared in pkg. File name mirrors CGF sharding.
type PkgShard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pkg           string                 `protobuf:"bytes,1,opt,name=pkg,proto3" json:"pkg,omitempty"`
	Callers       []*CallerEdges         `protobuf:"bytes,2,rep,name=callers,proto3" json:"callers,omitempty"`
	Types         []*TypeFingerprint     `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	Ifaces        []*IfaceFingerprint    `protobuf:"bytes,4,rep,name=ifaces,proto3" json:"ifaces,omitempty"`
	SatPairs      []*SatPair             `protobuf:"bytes,5,rep,name=sat_pairs,json=satPairs,proto3" json:"sat_pairs,omitempty"` // keyed by implementing type's package
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PkgShard) Reset() {
	*x = PkgShard{}
	mi := &file_cgstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PkgShard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkgShard) ProtoMessage() {}

func (x *PkgShard) ProtoReflect() protoreflect.Message {
	mi := &file_cgstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkgShard.ProtoReflect.Descriptor instead.
func (*PkgShard) Descriptor() ([]byte, []int) {
	return file_cgstore_proto_rawDescGZIP(), []int{1}
}

func (x *PkgShard) GetPkg() string {
	if x != nil {
		return x.Pkg
	}
	return ""
}

func (x *PkgShard) GetCallers() []*CallerEdges {
	if x != nil {
		return x.Callers
	}
	return nil
}

func (x *PkgShard) GetTypes() []*TypeFingerprint {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *PkgShard) GetIfaces() []*IfaceFingerprint {
	if x != nil {
		return x.Ifaces
	}
	return nil
}

func (x *PkgShard) GetSatPairs() []*SatPair {
	if x != nil {
		return x.SatPairs
	}
	return nil
}

// CallerEdges: all persisted dispatch sites of one function. Only sites the
// live resolver actually resolved (targets or capped-opaque) are stored;
// absent sites replay as unresolved — byte-identical to live behavior.
type CallerEdges struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CallerIid  []byte                 `protobuf:"bytes,1,opt,name=caller_iid,json=callerIid,proto3" json:"caller_iid,omitempty"`
	NCallsites uint32                 `protobuf:"varint,2,opt,name=n_callsites,json=nCallsites,proto3" json:"n_callsites,omitempty"` // TOTAL CallInstruction count in the caller (validation:
	// must equal the re-enumerated count on reload)
	Sites         []*SiteEdge `protobuf:"bytes,3,rep,name=sites,proto3" json:"sites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallerEdges) Reset() {
	*x = CallerEdges{}
	mi := &file_cgstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerEdges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerEdges) ProtoMessage() {}

func (x *CallerEdges) ProtoReflect() protoreflect.Message {
	mi := &file_cgstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerEdges.ProtoReflect.Descriptor instead.
func (*CallerEdges) Descriptor() ([]byte, []int) {
	return file_cgstore_proto_rawDescGZIP(), []int{2}
}

func (x *CallerEdges) GetCallerIid() []byte {
	if x != nil {
		return x.CallerIid
	}
	return nil
}

func (x *CallerEdges) GetNCallsites() uint32 {
	if x != nil {
		return x.NCallsites
	}
	return 0
}

func (x *CallerEdges) GetSites() []*SiteEdge {
	if x != nil {
		return x.Sites
	}
	return nil
}

// SiteEdge keys a site by the same ordinal the CGF emits as CallSite.Id: the
// index of the ssa.CallInstruction in deterministic fn.Blocks/Instrs order.
type SiteEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallsiteId    uint32                 `protobuf:"varint,1,opt,name=callsite_id,json=callsiteId,proto3" json:"callsite_id,omitempty"`
	CalleeIids    [][]byte               `protobuf:"bytes,2,rep,name=callee_iids,json=calleeIids,proto3" json:"callee_iids,omitempty"`       // FQN-sorted, exactly the live resolver's order
	OpaqueByCap   bool                   `protobuf:"varint,3,opt,name=opaque_by_cap,json=opaqueByCap,proto3" json:"opaque_by_cap,omitempty"` // capped site: callee_iids empty, replay opaque
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`                       // = 1/len(callee_iids); persisted as cross-check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteEdge) Reset() {
	*x = SiteEdge{}
	mi := &file_cgstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteEdge) ProtoMessage() {}

func (x *SiteEdge) ProtoReflect() protoreflect.Message {
	mi := &file_cgstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteEdge.ProtoReflect.Descriptor instead.
func (*SiteEdge) Descriptor() ([]byte, []int) {
	return file_cgstore_proto_rawDescGZIP(), []int{3}
}

func (x *SiteEdge) GetCallsiteId() uint32 {
	if x != nil {
		return x.CallsiteId
	}
	return 0
}

func (x *SiteEdge) GetCalleeIids() [][]byte {
	if x != nil {
		return x.CalleeIids
	}
	return nil
}

func (x *SiteEdge) GetOpaqueByCap() bool {
	if x != nil {
		return x.OpaqueByCap
	}
	return false
}

func (x *SiteEdge) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Method-set fingerprint of a named type (spec §5 / synchronous-floyd design):
// sha256 over the pointer method set sorted by types.Func.Id(), each entry
// Id + canonical signature + an "also in value set" bit. No Ph1 consumer —
// persisted now so Ph2's satisfaction delta has a base table to diff against.
type TypeFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeKey       string                 `protobuf:"bytes,1,opt,name=type_key,json=typeKey,proto3" json:"type_key,omitempty"` // types.TypeString with full-path qualifier
	Msfp          []byte                 `protobuf:"bytes,2,opt,name=msfp,proto3" json:"msfp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeFingerprint) Reset() {
	*x = TypeFingerprint{}
	mi := &file_cgstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeFingerprint) ProtoMessage() {}

func (x *TypeFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_cgstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeFingerprint.ProtoReflect.Descriptor instead.
func (*TypeFingerprint) Descriptor() ([]byte, []int) {
	return file_cgstore_proto_rawDescGZIP(), []int{4}
}

func (x *TypeFingerprint) GetTypeKey() string {
	if x != nil {
		return x.TypeKey
	}
	return ""
}

func (x *TypeFingerprint) GetMsfp() []byte {
	if x != nil {
		return x.Msfp
	}
	return nil
}

type IfaceFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IfaceKey      string                 `protobuf:"bytes,1,opt,name=iface_key,json=ifaceKey,proto3" json:"iface_key,omitempty"`
	Ifp           []byte                 `protobuf:"bytes,2,opt,name=ifp,proto3" json:"ifp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IfaceFingerprint) Reset() {
	*x = IfaceFingerprint{}
	mi := &file_cgstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IfaceFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfaceFingerprint) ProtoMessage() {}

func (x *IfaceFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_cgstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfaceFingerprint.ProtoReflect.Descriptor instead.
func (*IfaceFingerprint) Descriptor() ([]byte, []int) {
	return file_cgstore_proto_rawDescGZIP(), []int{5}
}

func (x *IfaceFingerprint) GetIfaceKey() string {
	if x != nil {
		return x.IfaceKey
	}
	return ""
}

func (x *IfaceFingerprint) GetIfp() []byte {
	if x != nil {
		return x.Ifp
	}
	return nil
}

// A materialized `type ⊨ interface` satisfaction fact.
type SatPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeKey       string                 `protobuf:"bytes,1,opt,name=type_key,json=typeKey,proto3" json:"type_key,omitempty"`
	IfaceKey      string                 `protobuf:"bytes,2,opt,name=iface_key,json=ifaceKey,proto3" json:"iface_key,omitempty"`
	PointerOnly   bool                   `protobuf:"varint,3,opt,name=pointer_only,json=pointerOnly,proto3" json:"pointer_only,omitempty"` // *T satisfies but T does not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatPair) Reset() {
	*x = SatPair{}
	mi := &file_cgstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatPair) ProtoMessage() {}

func (x *SatPair) ProtoReflect() protoreflect.Message {
	mi := &file_cgstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatPair.ProtoReflect.Descriptor instead.
func (*SatPair) Descriptor() ([]byte, []int) {
	return file_cgstore_proto_rawDescGZIP(), []int{6}
}

func (x *SatPair) GetTypeKey() string {
	if x != nil {
		return x.TypeKey
	}
	return ""
}

func (x *SatPair) GetIfaceKey() string {
	if x != nil {
		return x.IfaceKey
	}
	return ""
}

func (x *SatPair) GetPointerOnly() bool {
	if x != nil {
		return x.PointerOnly
	}
	return false
}

type Meta_Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pkg           string                 `protobuf:"bytes,1,opt,name=pkg,proto3" json:"pkg,omitempty"`       // package import path
	Sha256        []byte                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"` // content hash of the shard file as written
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta_Shard) Reset() {
	*x = Meta_Shard{}
	mi := &file_cgstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta_Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta_Shard) ProtoMessage() {}

func (x *Meta_Shard) ProtoReflect() protoreflect.Message {
	mi := &file_cgstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta_Shard.ProtoReflect.Descriptor instead.
func (*Meta_Shard) Descriptor() ([]byte, []int) {
	return file_cgstore_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Meta_Shard) GetPkg() string {
	if x != nil {
		return x.Pkg
	}
	return ""
}

func (x *Meta_Shard) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

var File_cgstore_proto protoreflect.FileDescriptor

const file_cgstore_proto_rawDesc = "" +
	"\n" +
	"\rcgstore.proto\x12\x13panopticode.cgstore\"\xca\x05\n" +
	"\x04Meta\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x03 \x01(\tR\tcommitSha\x12\x1d\n" +
	"\n" +
	"parent_sha\x18\x04 \x01(\tR\tparentSha\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12!\n" +
	"\fpcfe_version\x18\x06 \x01(\tR\vpcfeVersion\x12!\n" +
	"\fgo_toolchain\x18\a \x01(\tR\vgoToolchain\x12\x17\n" +
	"\acg_mode\x18\b \x01(\tR\x06cgMode\x12\x13\n" +
	"\x05cap_n\x18\t \x01(\rR\x04capN\x12#\n" +
	"\rexclude_mocks\x18\n" +
	" \x01(\bR\fexcludeMocks\x12\x1e\n" +
	"\vfn_set_hash\x18\v \x01(\fR\tfnSetHash\x12!\n" +
	"\fcreated_unix\x18\f \x01(\x03R\vcreatedUnix\x12(\n" +
	"\x10dispatch_wall_ms\x18\r \x01(\x03R\x0edispatchWallMs\x12#\n" +
	"\rgeneric_edges\x18\x0e \x01(\x05R\fgenericEdges\x12*\n" +
	"\x11sites_all_generic\x18\x0f \x01(\x05R\x0fsitesAllGeneric\x12,\n" +
	"\x12sites_some_generic\x18\x10 \x01(\x05R\x10sitesSomeGeneric\x12\x1f\n" +
	"\vfield_paths\x18\x12 \x01(\bR\n" +
	"fieldPaths\x12!\n" +
	"\fclosure_flow\x18\x13 \x01(\bR\vclosureFlow\x127\n" +
	"\x06shards\x18\x11 \x03(\v2\x1f.panopticode.cgstore.Meta.ShardR\x06shards\x1a1\n" +
	"\x05Shard\x12\x10\n" +
	"\x03pkg\x18\x01 \x01(\tR\x03pkg\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\"\x8e\x02\n" +
	"\bPkgShard\x12\x10\n" +
	"\x03pkg\x18\x01 \x01(\tR\x03pkg\x12:\n" +
	"\acallers\x18\x02 \x03(\v2 .panopticode.cgstore.CallerEdgesR\acallers\x12:\n" +
	"\x05types\x18\x03 \x03(\v2$.panopticode.cgstore.TypeFingerprintR\x05types\x12=\n" +
	"\x06ifaces\x18\x04 \x03(\v2%.panopticode.cgstore.IfaceFingerprintR\x06ifaces\x129\n" +
	"\tsat_pairs\x18\x05 \x03(\v2\x1c.panopticode.cgstore.SatPairR\bsatPairs\"\x82\x01\n" +
	"\vCallerEdges\x12\x1d\n" +
	"\n" +
	"caller_iid\x18\x01 \x01(\fR\tcallerIid\x12\x1f\n" +
	"\vn_callsites\x18\x02 \x01(\rR\n" +
	"nCallsites\x123\n" +
	"\x05sites\x18\x03 \x03(\v2\x1d.panopticode.cgstore.SiteEdgeR\x05sites\"\x90\x01\n" +
	"\bSiteEdge\x12\x1f\n" +
	"\vcallsite_id\x18\x01 \x01(\rR\n" +
	"callsiteId\x12\x1f\n" +
	"\vcallee_iids\x18\x02 \x03(\fR\n" +
	"calleeIids\x12\"\n" +
	"\ropaque_by_cap\x18\x03 \x01(\bR\vopaqueByCap\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"@\n" +
	"\x0fTypeFingerprint\x12\x19\n" +
	"\btype_key\x18\x01 \x01(\tR\atypeKey\x12\x12\n" +
	"\x04msfp\x18\x02 \x01(\fR\x04msfp\"A\n" +
	"\x10IfaceFingerprint\x12\x1b\n" +
	"\tiface_key\x18\x01 \x01(\tR\bifaceKey\x12\x10\n" +
	"\x03ifp\x18\x02 \x01(\fR\x03ifp\"d\n" +
	"\aSatPair\x12\x19\n" +
	"\btype_key\x18\x01 \x01(\tR\atypeKey\x12\x1b\n" +
	"\tiface_key\x18\x02 \x01(\tR\bifaceKey\x12!\n" +
	"\fpointer_only\x18\x03 \x01(\bR\vpointerOnlyBAZ?github.com/panoptiorg/panoptife-go/internal/cgstorepb;cgstorepbb\x06proto3"

var (
	file_cgstore_proto_rawDescOnce sync.Once
	file_cgstore_proto_rawDescData []byte
)

func file_cgstore_proto_rawDescGZIP() []byte {
	file_cgstore_proto_rawDescOnce.Do(func() {
		file_cgstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cgstore_proto_rawDesc), len(file_cgstore_proto_rawDesc)))
	})
	return file_cgstore_proto_rawDescData
}

var file_cgstore_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cgstore_proto_goTypes = []any{
	(*Meta)(nil),             // 0: panopticode.cgstore.Meta
	(*PkgShard)(nil),         // 1: panopticode.cgstore.PkgShard
	(*CallerEdges)(nil),      // 2: panopticode.cgstore.CallerEdges
	(*SiteEdge)(nil),         // 3: panopticode.cgstore.SiteEdge
	(*TypeFingerprint)(nil),  // 4: panopticode.cgstore.TypeFingerprint
	(*IfaceFingerprint)(nil), // 5: panopticode.cgstore.IfaceFingerprint
	(*SatPair)(nil),          // 6: panopticode.cgstore.SatPair
	(*Meta_Shard)(nil),       // 7: panopticode.cgstore.Meta.Shard
}
var file_cgstore_proto_depIdxs = []int32{
	7, // 0: panopticode.cgstore.Meta.shards:type_name -> panopticode.cgstore.Meta.Shard
	2, // 1: panopticode.cgstore.PkgShard.callers:type_name -> panopticode.cgstore.CallerEdges
	4, // 2: panopticode.cgstore.PkgShard.types:type_name -> panopticode.cgstore.TypeFingerprint
	5, // 3: panopticode.cgstore.PkgShard.ifaces:type_name -> panopticode.cgstore.IfaceFingerprint
	6, // 4: panopticode.cgstore.PkgShard.sat_pairs:type_name -> panopticode.cgstore.SatPair
	3, // 5: panopticode.cgstore.CallerEdges.sites:type_name -> panopticode.cgstore.SiteEdge
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cgstore_proto_init() }
func file_cgstore_proto_init() {
	if File_cgstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cgstore_proto_rawDesc), len(file_cgstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cgstore_proto_goTypes,
		DependencyIndexes: file_cgstore_proto_depIdxs,
		MessageInfos:      file_cgstore_proto_msgTypes,
	}.Build()
	File_cgstore_proto = out.File
	file_cgstore_proto_goTypes = nil
	file_cgstore_proto_depIdxs = nil
}
